version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:4000:4000"
    environment:
      - MIX_ENV=prod
      - PORT=4000
    restart: unless-stopped
